In [2]:
%pip install numpy

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the 'c:\Users\rokas\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.



     --------------------------------------- 14.8/14.8 MB 32.8 MB/s eta 0:00:00


# 2D array

In [6]:
a_list = [
    [1,2,3,4],
    [5,4,6,7],
    [9,10,11,12]
]


6
[9, 10, 11, 12]
[1, 5, 9]


In [7]:
print(a_list[1][2])
print(a_list[2])
print( [ row [0] for row in a_list ])

6
[9, 10, 11, 12]
[1, 5, 9]


In [8]:
import numpy as np

In [10]:
np_array = np.array(a_list)
print(np_array)

[[ 1  2  3  4]
 [ 5  4  6  7]
 [ 9 10 11 12]]


# 1D array


In [12]:
array_1d = np.array([1,58,97,3,74])
print(array_1d)
list_1d = [1,58,97,3,74]
print(list_1d *3)

print([ num * 3 for num in list_1d])

[ 1 58 97  3 74]
[1, 58, 97, 3, 74, 1, 58, 97, 3, 74, 1, 58, 97, 3, 74]
[3, 174, 291, 9, 222]


# 3D array

In [15]:
arr_3d = np.array([
    [
    [1,2,3],
    [4,5,6]
    ],
    [
    [1,2,3],
    [4,5,6]
    ]
]
)
print(arr_3d)

print(arr_3d.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)


In [21]:
arr_3d[ :, :, 2] = 10
print(arr_3d, '\n')

print('Task','\n')
arr_3d[1,0,0:2] = 50

print(arr_3d)

[[[ 1  2 10]
  [ 4  5 10]]

 [[50 50 10]
  [ 4  5 10]]] 

Task 

[[[ 1  2 10]
  [ 4  5 10]]

 [[50 50 10]
  [ 4  5 10]]]


In [28]:

size=1_000_000

In [25]:
# %%timeit

py_list = list(range(size))

In [26]:
len(py_list)

1000000

In [31]:
%%timeit

np_arr = np.arange(size)

840 µs ± 13.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [33]:
%%timeit

[ num * 2 for num in py_list]

40.4 ms ± 390 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [34]:
%%timeit

np_arr *2

818 µs ± 16.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [35]:
%pip install pandas


     --------------------------------------- 10.4/10.4 MB 20.5 MB/s eta 0:00:00
     ------------------------------------- 499.4/499.4 KB 30.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\rokas\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [36]:
import pandas as pd

In [38]:
df = pd.DataFrame(
    [ ['Jan',58,42,74,22,2.05],
    ['Feb',61,45,78,26,3.02],
    ['Mar',65,48,84,25,2.34],
    ['Apr',67,50,92,28,1.02],
    ['May',71,53,98,35,0.48],
    ['Jun',75,56,107,41,0.11],
    ['Jul',77,58,105,44,0.0],
    ['Aug',77,59,102,43,0.03],
    ['Sep',77,57,103,40,0.17],
    ['Oct',73,54,96,34,0.81],
    ['Nov',64,48,84,30,1.7],
    ['Dec',58,None,None,21,2.56],
    ['Dec',58,42,73,21,2.56] ],
    columns = ['month','avg_high','avg_low','record_high','record_low','avg_precipitation'])

df

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0    Jan        58     42.0         74.0          22               2.05
1    Feb        61     45.0         78.0          26               3.02
2    Mar        65     48.0         84.0          25               2.34
3    Apr        67     50.0         92.0          28               1.02
4    May        71     53.0         98.0          35               0.48
5    Jun        75     56.0        107.0          41               0.11
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
8    Sep        77     57.0        103.0          40               0.17
9    Oct        73     54.0         96.0          34               0.81
10   Nov        64     48.0         84.0          30               1.70
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   month              13 non-null     object 
 1   avg_high           13 non-null     int64  
 2   avg_low            12 non-null     float64
 3   record_high        12 non-null     float64
 4   record_low         13 non-null     int64  
 5   avg_precipitation  13 non-null     float64
dtypes: float64(3), int64(2), object(1)
memory usage: 752.0+ bytes


In [40]:
df.describe()

avg_high    avg_low  record_high  record_low  avg_precipitation
count  13.000000  12.000000    12.000000   13.000000          13.000000
mean   67.769231  51.000000    91.333333   31.538462           1.296154
std     7.639305   6.060303    12.323911    8.501131           1.115210
min    58.000000  42.000000    73.000000   21.000000           0.000000
25%    61.000000  47.250000    82.500000   25.000000           0.170000
50%    67.000000  51.500000    94.000000   30.000000           1.020000
75%    75.000000  56.250000   102.250000   40.000000           2.340000
max    77.000000  59.000000   107.000000   44.000000           3.020000

In [41]:
df.tail(3)

month  avg_high  avg_low  record_high  record_low  avg_precipitation
10   Nov        64     48.0         84.0          30               1.70
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56